
spring:
  datasource:
#    при запуске на виндовс сайта и телеграм бота одновременно
#    url: jdbc:h2:file:C:/Users/Dell/IdeaProjects/cloneAmenityReservationSystem;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:amenity-reservation-system
    username: sa
    password:
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  #Email
  mail:
    host: mail.gmx.com
    port: 587
    username: aqua.aqua@gmx.com
    password: adminAqua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true
springdoc:
  pathsToMatch: /api/**

